- name: start cassandra
  service: name=cassandra state=started enabled=yes

- name: restart cassandra
  service: name=cassandra state=restarted enabled=yes

- name: Restart server
  command: shutdown -r now "Reboot triggered by Ansible"
  async: 0
  poll: 0
  any_errors_fatal: True
#  ignore_errors: true
- name: Wait for server to restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=1
      timeout=300
