---
- name: Reload systemd
  command: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Restart opscenter
  service: name=opscenterd state=restarted
  notify: Sleep

- name: Sleep
  pause: seconds=30
- name: Restart server
  command: shutdown -r now "Reboot triggered by Ansible"
  async: 0 
  poll: 0 
  any_errors_fatal: True
#  ignore_errors: true
- name: Wait for server to restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=1
      timeout=300
