---
- name: Reload systemd
  command: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Restart opscenter
  service: name=opscenterd state=restarted
  notify: Sleep

- name: Sleep
  pause: seconds=30
